export const CUISINE_TYPES = {
  afghani: "Afghani",
  african: "African",
  american: "American",
  arabian: "Arabian",
  argentine: "Argentine",
  armenian: "Armenian",
  asian_fusion: "Asian Fusion",
  australian: "Australian",
  austrian: "Austrian",
  bangladeshi: "Bangladeshi",
  barbecue: "Barbecue",
  basque: "Basque",
  belgian: "Belgian",
  brazilian: "Brazilian",
  breakfast_brunch: "Breakfast & Brunch",
  british: "British",
  buffets: "Buffets",
  burgers: "Burgers",
  burmese: "Burmese",
  cajun: "Cajun",
  cambodian: "Cambodian",
  caribbean: "Caribbean",
  chinese: "Chinese",
  colombian: "Colombian",
  creperies: "Creperies",
  cuban: "Cuban",
  czech: "Czech",
  delis: "Delis",
  diners: "Diners",
  ethiopian: "Ethiopian",
  filipino: "Filipino",
  fondue: "Fondue",
  french: "French",
  gastropubs: "Gastropubs",
  german: "German",
  greek: "Greek",
  hawaiian: "Hawaiian",
  himalayan: "Himalayan",
  hungarian: "Hungarian",
  indpak: "Indian",
  indonesian: "Indonesian",
  irish: "Irish",
  italian: "Italian",
  japanese: "Japanese",
  korean: "Korean",
  kosher: "Kosher",
  laotian: "Laotian",
  latin_american: "Latin American",
  malaysian: "Malaysian",
  mediterranean: "Mediterranean",
  mexican: "Mexican",
  middle_eastern: "Middle Eastern",
  mongolian: "Mongolian",
  moroccan: "Moroccan",
  nepalese: "Nepalese",
  new_american: "New American",
  pakistani: "Pakistani",
  persian: "Persian",
  peruvian: "Peruvian",
  pizza: "Pizza",
  polish: "Polish",
  portuguese: "Portuguese",
  russian: "Russian",
  salad: "Salad",
  sandwiches: "Sandwiches",
  scandinavian: "Scandinavian",
  scottish: "Scottish",
  seafood: "Seafood",
  singaporean: "Singaporean",
  slovakian: "Slovakian",
  somali: "Somali",
  soul_food: "Soul Food",
  south_african: "South African",
  southern: "Southern",
  spanish: "Spanish",
  srilankan: "Sri Lankan",
  steakhouses: "Steakhouses",
  sushi: "Sushi",
  swedish: "Swedish",
  swiss: "Swiss",
  taiwanese: "Taiwanese",
  tapas: "Tapas",
  "tex-mex": "Tex-Mex",
  thai: "Thai",
  turkish: "Turkish",
  ukrainian: "Ukrainian",
  vegan: "Vegan",
  vegetarian: "Vegetarian",
  vietnamese: "Vietnamese",
  waffles: "Waffles",
  wraps: "Wraps",
};

export const cuisineArray = Object.entries(CUISINE_TYPES).map(([alias, cuisine]) => ({
  alias,
  cuisine,
}));